### PR TITLE
po: Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by hosiet**
This pull request helps to refresh and complete lightdm translation for Simplified Chinese (`zh_CN`).

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by hosiet** [comment]
The CLA check CI seems to have returned weird result: it says my GitHub username to be `HttpError: User does not exist or is not a member of the organization`. My username definitely exists, and I have no idea what is "member of the organization". Does the organization refer to Canonical?

Also, I have definitely signed the CLA, yet the CI check still cannot get such data. My launchpad profile is https://launchpad.net/~hosiet .

I would be grateful if anyone could provide further instruction on how to proceed. Do I need to sign the CLA again? Just to be clear, I have signed and agree the Canonical CLA at https://ubuntu.com/legal/contributors/agreement , and I hereby agree to release my contribution in this pull request ( https://github.com/canonical/lightdm/pull/276 ) to the public domain or have it provided to Canonical for any use without any extra terms, whichever is more permissive.

**Comment by JezerM** [comment]
Maybe this could help: make sure your launchpad main email account is the same as your GitHub account.

**Comment by hosiet** [comment]
Thanks, I believe the main email address across launchpad and GitHub accounts are all the same, which is the same as on the CLA form.

**Comment by robert-ancell** [comment]
Closing this as I am not able to review translations. This needs to be fixed by using [a translation service](https://github.com/canonical/lightdm/issues/258). I appreciate this is frustrating for your contribution, but I think it is misleading to leave a PR open that is not going to be merged. If someone has a solution to automate this please add it to the linked issues above.

**Pull request closed without merging**
