### PR TITLE
Fix for other libcs

### PR DESCRIPTION
**Pull request by listout**
I came across these two issues while trying to build lightdm on musl libc. Some of the patches are based on other Linux distro's patches (for example Alpine and Void).

The second commit where I do `ifdef __GLIBC__` can be done in a better way, I'm hoping someone can help me figure that out.

### CODE REVIEW

**Comment by listout** [comment]
Fix the failing test and added another fix.

**Comment by robert-ancell** [comment]
@listout did you go through the CLA process? Thanks.

**Comment by listout** [comment]
@robert-ancell nope. Should I?

**Comment by qwertychouskie** [comment]
[github-actions](https://github.com/apps/github-actions) bot commented [on Jul 21](https://github.com/canonical/lightdm/pull/261#issuecomment-1191532460)
Hey! listout has not signed the Canonical CLA which is required to get this contribution merged on this project.

Please head over to [ubuntu.com/legal/contributors](https://ubuntu.com/legal/contributors) to read more about it.

**Comment by robert-ancell** [comment]
Closing this as the CLA has not been signed as required. Please re-open if you are able to, thanks!

**Pull request closed without merging**
